CREATE TABLE AIR_MEMBER(
    ID VARCHAR2(20) PRIMARY KEY,
    PWD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(20) UNIQUE,
    BIRTH VARCHAR2(20) NOT NULL,
    GRADE NUMBER(10) NOT NULL,
    AUTH NUMBER(2) NOT NULL,
    DEL NUMBER(2) NOT NULL,
    CONSTRAINT CHK_AUTH CHECK(AUTH >= 0 AND AUTH < 2),
    CONSTRAINT CHK_DEL CHECK(DEL >= 0 AND DEL < 2)
);

INSERT INTO AIR_MEMBER 
VALUES('admin', 'admin', 'admin', '010-8619-8323', 'admin@gmail.com', '1994-01-27', 50, 1, 0);

CREATE TABLE AIR_INFO(
    A_NUM NUMBER(20) PRIMARY KEY,
    A_NAME VARCHAR2(50) NOT NULL,
    A_SEAT_ONE NUMBER(10) NOT NULL,
    A_SEAT_TWO NUMBER(10) NOT NULL,
    A_SEAT_THREE NUMBER(10) NOT NULL,
    A_LOCATION_S VARCHAR2(100) NOT NULL,
    A_LOCATION_E VARCHAR2(100) NOT NULL,
    A_TIME_S NUMBER(12) NOT NULL,
    A_TIME_E NUMBER(12) NOT NULL,
    A_PRICE NUMBER(10) NOT NULL
);
DROP TABLE AIR_PACKAGE
CASCADE CONSTRAINT;

SELECT * FROM AIR_INFO;
CREATE SEQUENCE SEQ_A_NUM
START WITH 1 INCREMENT BY 1;

CREATE TABLE AIR_PACKAGE(
    P_NUM NUMBER(20),
    P_NAME VARCHAR2(50) PRIMARY KEY,
    P_PRICE NUMBER(20) NOT NULL,
    P_SCHEDULE VARCHAR2(50) NOT NULL,
    P_CONTENT VARCHAR2(4000),
    P_COUNTRY VARCHAR2(50) NOT NULL,
    P_READCOUNT NUMBER(10) NOT NULL,
    P_BUYCOUNT NUMBER(10) NOT NULL,
    P_LIKE NUMBER(10) NOT NULL
);
CREATE SEQUENCE SEQ_P_NUM
START WITH 1 INCREMENT BY 1;


CREATE TABLE AIR_RESERVE(
    R_SEQ NUMBER(10) PRIMARY KEY,
    R_ID VARCHAR2(20) NOT NULL,
    R_NUM NUMBER(20) NOT NULL,
    R_NAME VARCHAR2(20) NOT NULL,
    R_WDATE DATE,
    CONSTRAINT FK_ID FOREIGN KEY(R_ID) REFERENCES AIR_MEMBER(ID),
    CONSTRAINT FK_NUM FOREIGN KEY(R_NUM) REFERENCES AIR_INFO(A_NUM),
    CONSTRAINT FK_NAME FOREIGN KEY(R_NAME) REFERENCES AIR_PACKAGE(P_NAME)
);



CREATE TABLE BBS_QNA(
    SEQ NUMBER(10) PRIMARY KEY,
    ID VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(10) NOT NULL,
    
    CONSTRAINT FK_BBSQNA_ID FOREIGN KEY(ID) REFERENCES AIR_MEMBER(ID)
);



CREATE TABLE BBS_NOTICE(
    SEQ NUMBER(10) PRIMARY KEY,
    ID VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(10) NOT NULL,
    
    CONSTRAINT FK_BBSNOTICE_ID FOREIGN KEY(ID) REFERENCES AIR_MEMBER(ID)
);



CREATE TABLE BBS_CS(
    SEQ NUMBER(10) PRIMARY KEY,
    ID VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    WDATE DATE NOT NULL,
    REF NUMBER(8) NOT NULL,
    STEP NUMBER(8) NOT NULL,
    DEPTH NUMBER(8) NOT NULL,
    PARENT NUMBER(8) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    READCOUNT NUMBER(10) NOT NULL,
    PROCESS VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(100) NOT NULL,
    SECRET NUMBER(10),    
    CONSTRAINT FK_BBSCS_ID FOREIGN KEY(ID) REFERENCES AIR_MEMBER(ID)
);






DROP TABLE AIR_PACKAGE
CASCADE CONSTRAINTS PURGE;




------------------------------------------------------------------------------------------





DROP TABLE AIR_PACKAGE
CASCADE CONSTRAINTS;

CREATE TABLE AIR_PACKAGE(
    P_NUM NUMBER(20),
    P_NAME VARCHAR2(50) PRIMARY KEY,
    P_PRICE NUMBER(20) NOT NULL,
    P_SCHEDULE VARCHAR2(50) NOT NULL,
    P_CONTENT VARCHAR2(4000),
    P_COUNTRY VARCHAR2(50) NOT NULL,
    P_READCOUNT NUMBER(10) NOT NULL,
    P_BUYCOUNT NUMBER(10) NOT NULL,
    P_LIKE NUMBER(10) NOT NULL
);
CREATE SEQUENCE SEQ_P_NUM
START WITH 1 INCREMENT BY 1;

DROP TABLE AIR_INFO
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_A_NUM;

CREATE TABLE AIR_INFO2(
    A_NUM NUMBER(20) PRIMARY KEY,
    A_NAME VARCHAR2(50) NOT NULL,
    A_SEAT_ONE NUMBER(10) NOT NULL,
    A_SEAT_TWO NUMBER(10) NOT NULL,
    A_SEAT_THREE NUMBER(10) NOT NULL,
    A_LOCATION_S VARCHAR2(100) NOT NULL,
    A_LOCATION_E VARCHAR2(100) NOT NULL,
    A_TIME_S VARCHAR2(12) NOT NULL,
    A_TIME_E VARCHAR2(12) NOT NULL,
    A_PRICE NUMBER(10) NOT NULL
);

SELECT * FROM AIR_INFO;
CREATE SEQUENCE SEQ_A_NUM
START WITH 1 INCREMENT BY 1;

SELECT * FROM AIR_INFO2
WHERE A_TIME_S LIKE ('20170822%') AND A_TIME_E LIKE ('20170901%');


DROP TABLE AIR_PACKAGE
CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE SEQ_P_NUM;

CREATE TABLE AIR_PACKAGE(
    P_NUM NUMBER(20) PRIMARY KEY,
    P_NAME VARCHAR2(50),
    P_PRICE NUMBER(20) NOT NULL,
    P_SCHEDULE VARCHAR2(50) NOT NULL,
    P_CONTENT VARCHAR2(4000),
    P_COUNTRY VARCHAR2(50) NOT NULL,
    P_READCOUNT NUMBER(10) NOT NULL,
    P_BUYCOUNT NUMBER(10) NOT NULL,
    P_LIKE NUMBER(10) NOT NULL
);
CREATE SEQUENCE SEQ_P_NUM
START WITH 1 INCREMENT BY 1;